CREATE SCHEMA TELEGRAM;

USE TELEGRAM;

CREATE TABLE QUESTION
(
  ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  TEXT CLOB
);
CREATE UNIQUE INDEX QUESTION_ID_UINDEX ON question (ID);

CREATE TABLE PHOTO
(
  ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  QUEST_ID INT NOT NULL,
  FILE_PATH CLOB NOT NULL,
  TEXT CLOB,
  CONSTRAINT PHOTO_QUESTION_ID_fk FOREIGN KEY (QUEST_ID) REFERENCES QUESTION (ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX photo_id_uindex ON photo (id);

CREATE TABLE ANSWER
(
  ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  QUEST_ID INT NOT NULL,
  TEXT CLOB,
  COMMENT CLOB,
  CONSTRAINT ANSWER_QUESTION_ID_fk FOREIGN KEY (QUEST_ID) REFERENCES QUESTION (ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX ANSWER_id_uindex ON ANSWER (ID);